/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.theaterbooking.view;

import com.ijse.theaterbooking.connector.ServerConnector;
import com.ijse.theaterbooking.controller.MovieController;
import com.ijse.theaterbooking.model.Movies;
import com.toedter.calendar.DateUtil;
import com.toedter.calendar.IDateEvaluator;
import com.toedter.calendar.JCalendar;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sanu Vithanage
 */
public class BookingStepOne extends javax.swing.JPanel {

    private String filmName;
    private String filmTime;
    private String usrID;
    private String bookingTid;
    private String userName;
    private String filmID;
    ///////////////////

    private String seatClass;
    private String cato;
    private boolean response = false;

    private double goldFull = 780.00;
    private double goldHalf = 650.00;
    private double odcTic = 450.00;
    private double boxTic = 1650.00;

    /**
     * Creates new form BookingStepOne
     */
    public BookingStepOne(String filmName, String filmTime, String userName, String usrID, String filmID) throws ParseException {
        initComponents();
        this.filmName = filmName;
        this.filmTime = filmTime;
        this.userName = userName;
        this.usrID = usrID;
        this.filmID = filmID;
        setBokingDate();
        nameSetin();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookinDe = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        goldFullPrice = new javax.swing.JLabel();
        goldHalfPrice = new javax.swing.JLabel();
        odc = new javax.swing.JLabel();
        movieNa1 = new javax.swing.JLabel();
        box = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        catagoryType = new javax.swing.JComboBox();
        halfTicket = new javax.swing.JComboBox();
        fullTickets = new javax.swing.JComboBox();
        movieT = new javax.swing.JLabel();
        movieNa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cccheck = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1000, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookinDe.setBackground(java.awt.Color.white);
        bookinDe.setRequestFocusEnabled(false);
        bookinDe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bookinDeKeyReleased(evt);
            }
        });
        add(bookinDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 150, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/nenenext.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 130, 60));

        goldFullPrice.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        goldFullPrice.setForeground(new java.awt.Color(255, 255, 255));
        goldFullPrice.setText("780.00");
        add(goldFullPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        goldHalfPrice.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        goldHalfPrice.setForeground(new java.awt.Color(255, 255, 255));
        goldHalfPrice.setText("650.00");
        add(goldHalfPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        odc.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        odc.setForeground(new java.awt.Color(255, 255, 255));
        odc.setText("450.00");
        add(odc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        movieNa1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 18)); // NOI18N
        movieNa1.setForeground(new java.awt.Color(255, 255, 255));
        movieNa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        movieNa1.setText("current prices");
        add(movieNa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 280, 30));

        box.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        box.setForeground(new java.awt.Color(255, 255, 255));
        box.setText("1600.00");
        add(box, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gold Full  :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gold Half  :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Odc            :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("BOX           :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        catagoryType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gold Class", "ODC", "Box" }));
        catagoryType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                catagoryTypeItemStateChanged(evt);
            }
        });
        catagoryType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catagoryTypeActionPerformed(evt);
            }
        });
        add(catagoryType, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 160, 40));

        halfTicket.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", " " }));
        halfTicket.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                halfTicketItemStateChanged(evt);
            }
        });
        add(halfTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 70, 30));

        fullTickets.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", " " }));
        fullTickets.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fullTicketsItemStateChanged(evt);
            }
        });
        add(fullTickets, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 70, 30));

        movieT.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        movieT.setForeground(new java.awt.Color(255, 51, 102));
        movieT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        movieT.setText("10.30");
        add(movieT, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 210, 60));

        movieNa.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        movieNa.setForeground(new java.awt.Color(255, 255, 255));
        movieNa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        movieNa.setText("Maya Sinhala Movie");
        add(movieNa, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 490, 60));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("No of half Tickets");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, -1, -1));

        cccheck.setForeground(new java.awt.Color(255, 255, 255));
        cccheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(cccheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 50, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Seat Catagoty");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Select Date");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/deef.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 300, 300));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("No of full Tickets");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/tt2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (response) {
            String resp;
            if (usrID.equals("01122")) {
                resp = "A";
            } else {
                resp = "U";
            }
            int uniqueId = (int) (System.currentTimeMillis() & 0xfffffff);
            bookingTid = resp + uniqueId;

            int fullTi = Integer.parseInt(fullTickets.getSelectedItem().toString());
            int halfTi = Integer.parseInt(halfTicket.getSelectedItem().toString());
            int fullSeat = fullTi + halfTi;
            double totalPrice = fullTi * goldFull + halfTi * goldHalf;
            double total = 0;
            if (fullSeat >= 1) {
                try {
                    Date dat = bookinDe.getDate();
                    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                    String bDate = dateFormat.format(dat);
                    com.ijse.theaterbooking.view.GoldClassBook goldclss = new com.ijse.theaterbooking.view.GoldClassBook(bookingTid, userName, bDate, usrID, filmName, filmTime, totalPrice, filmID, fullSeat);
                    com.ijse.theaterbooking.view.HomePage.mainPa.removeAll();
                    com.ijse.theaterbooking.view.HomePage.mainPa.add(goldclss);
                    goldclss.setVisible(true);
                    com.ijse.theaterbooking.view.HomePage.mainPa.updateUI();
                } catch (RuntimeException e) {
                } catch (NotBoundException ex) {
                    Logger.getLogger(BookingStepOne.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(BookingStepOne.class.getName()).log(Level.SEVERE, null, ex);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(BookingStepOne.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(BookingStepOne.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(BookingStepOne.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(BookingStepOne.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Select the Number Of Seats You want to Book");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Select a valid date..!");
        }


    }//GEN-LAST:event_jButton1MouseClicked

    private void catagoryTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catagoryTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catagoryTypeActionPerformed

    private void catagoryTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_catagoryTypeItemStateChanged
        cato = catagoryType.getSelectedItem().toString();
    }//GEN-LAST:event_catagoryTypeItemStateChanged

    private void fullTicketsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fullTicketsItemStateChanged

        try {
            MovieController mc = ServerConnector.getServerConnector().getMovieController();
            Movies searchMovie = mc.searchMovie(filmID);
            if (searchMovie != null) {

                String movieDuration = searchMovie.getMovieDuration();

                try {
                    SimpleDateFormat dateForma = new SimpleDateFormat("yyyy-MM-dd");
                    Date bookingD = bookinDe.getDate();
                    //String mDuration = dateFormat.format(bookingD);

                    Date closingD = dateForma.parse(movieDuration);
                    long timeadj2 = 24 * 60 * 60 * 1000;
                    Date closingD2 = new Date(closingD.getTime() + timeadj2);

                    Date nowe = new Date();
                    String today = dateForma.format(nowe);
                    Date todayT = dateForma.parse(today);
                    //long timeadj = 24 * 60 * 60 * 1000;
                    //Date newDate = new Date(todayT.getTime() - timeadj);

                    if (closingD2.after(bookingD) && todayT.before(bookingD)) {
                        cccheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/tiv2.png")));
                        response = true;
                    } else {
                        cccheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/wrt.png")));
                        response = false;
                    }
                } catch (ParseException ex) {
                    Logger.getLogger(BookingStepOne.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        } catch (NotBoundException ex) {
            Logger.getLogger(BookingStepOne.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(BookingStepOne.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(BookingStepOne.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BookingStepOne.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BookingStepOne.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(BookingStepOne.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(BookingStepOne.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_fullTicketsItemStateChanged

    private void halfTicketItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_halfTicketItemStateChanged
        try {
            MovieController mc = ServerConnector.getServerConnector().getMovieController();
            Movies searchMovie = mc.searchMovie(filmID);
            if (searchMovie != null) {

                String movieDuration = searchMovie.getMovieDuration();

                try {
                    SimpleDateFormat dateForma = new SimpleDateFormat("yyyy-MM-dd");
                    Date bookingD = bookinDe.getDate();
                    //String mDuration = dateFormat.format(bookingD);

                    Date closingD = dateForma.parse(movieDuration);
                    long timeadj2 = 24 * 60 * 60 * 1000;
                    Date closingD2 = new Date(closingD.getTime() + timeadj2);

                    Date nowe = new Date();
                    String today = dateForma.format(nowe);
                    Date todayT = dateForma.parse(today);
                    //long timeadj = 24 * 60 * 60 * 1000;
                    //Date newDate = new Date(todayT.getTime() - timeadj);

                    if (closingD2.after(bookingD) && todayT.before(bookingD)) {
                        cccheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/tiv2.png")));
                        response = true;
                    } else {
                        cccheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/wrt.png")));
                        response = false;
                    }
                } catch (ParseException ex) {
                    Logger.getLogger(BookingStepOne.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        } catch (NotBoundException ex) {
            Logger.getLogger(BookingStepOne.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MalformedURLException ex) {
            Logger.getLogger(BookingStepOne.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RemoteException ex) {
            Logger.getLogger(BookingStepOne.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BookingStepOne.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BookingStepOne.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(BookingStepOne.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(BookingStepOne.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_halfTicketItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bookinDeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bookinDeKeyReleased

    }//GEN-LAST:event_bookinDeKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static com.toedter.calendar.JDateChooser bookinDe;
    private javax.swing.JLabel box;
    private javax.swing.JComboBox catagoryType;
    private javax.swing.JLabel cccheck;
    private javax.swing.JComboBox fullTickets;
    private javax.swing.JLabel goldFullPrice;
    private javax.swing.JLabel goldHalfPrice;
    private javax.swing.JComboBox halfTicket;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel movieNa;
    private javax.swing.JLabel movieNa1;
    private javax.swing.JLabel movieT;
    private javax.swing.JLabel odc;
    // End of variables declaration//GEN-END:variables

    private void nameSetin() {
        movieNa.setText(filmName);
        movieT.setText(filmTime);
    }

    private void setBokingDate() throws ParseException {

        Date date = new Date();
        bookinDe.setDate(date);

    }

}
