/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.theaterbooking.view;

import java.io.File;
import java.io.IOException;
import java.util.Date;
import org.apache.commons.io.FileUtils;
import com.ijse.theaterbooking.connector.ServerConnector;
import com.ijse.theaterbooking.controller.BookDetailsController;
import com.ijse.theaterbooking.controller.MovieController;
import com.ijse.theaterbooking.model.Movies;
import static com.ijse.theaterbooking.view.GoldClassBook.resDetails;
import static com.ijse.theaterbooking.view.MovieManage.emp;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sanu Vithanage
 */
public class HomePage extends javax.swing.JFrame {

    private String userName;
    private String userId;
    private Calendar cal;
    private String day_night;
    private String time1;
    private String movieID;

    /**
     * Creates new form
     */
    public HomePage(String userName, String userID) throws ClassNotFoundException, NotBoundException, RemoteException, SQLException, IOException, MalformedURLException, FileNotFoundException, ParseException {
        initComponents();
        this.userName = userName;
        this.userId = userID;
        mainPa.setVisible(false);
        blackL.setVisible(false);
        btn1.setVisible(false);
        btn2.setVisible(false);
        btn3.setVisible(false);
        btn4.setVisible(false);
        gt1.setVisible(false);
        dateDate.setVisible(false);
        setDate();
        setTime();
        setMoviUpdates();
        setUser();
        sl.setVisible(false);
        usSecondL.setVisible(false);
        mmSecondL.setVisible(false);
        closeL.setVisible(false);
        setMoviUpdates();
        // moviSheduler();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateDate = new com.toedter.calendar.JDateChooser();
        gt1 = new javax.swing.JLabel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        mainPa = new javax.swing.JPanel();
        closeL = new javax.swing.JLabel();
        blackL = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        smView = new javax.swing.JLabel();
        lmView = new javax.swing.JLabel();
        tmView = new javax.swing.JLabel();
        fmView = new javax.swing.JLabel();
        mmFirstL = new javax.swing.JLabel();
        mmSecondL = new javax.swing.JLabel();
        usFirstL = new javax.swing.JLabel();
        usSecondL = new javax.swing.JLabel();
        fl = new javax.swing.JLabel();
        sl = new javax.swing.JLabel();
        uIDLabel = new javax.swing.JLabel();
        uNameLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        clock = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        backupBtn = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        movieTwoL = new javax.swing.JLabel();
        movieThreeL = new javax.swing.JLabel();
        movieFourL = new javax.swing.JLabel();
        movieOneL = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        filmOneButton = new javax.swing.JButton();
        filmThreeButton = new javax.swing.JButton();
        filnFourButton = new javax.swing.JButton();
        titleM1 = new javax.swing.JLabel();
        titleM3 = new javax.swing.JLabel();
        titleM2 = new javax.swing.JLabel();
        titleM4 = new javax.swing.JLabel();
        filmTwoButton = new javax.swing.JButton();
        movieTt3 = new javax.swing.JLabel();
        movieTt2 = new javax.swing.JLabel();
        movieTt4 = new javax.swing.JLabel();
        movieTt1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        animationL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(dateDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 530, 118, 28));

        gt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/trans.png"))); // NOI18N
        getContentPane().add(gt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 160, 70));

        btn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/checj.png"))); // NOI18N
        btn1.setContentAreaFilled(false);
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
        });
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 110, 50));

        btn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/checj.png"))); // NOI18N
        btn2.setContentAreaFilled(false);
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 110, 50));

        btn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/checj.png"))); // NOI18N
        btn3.setContentAreaFilled(false);
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 110, 50));

        btn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/checj.png"))); // NOI18N
        btn4.setContentAreaFilled(false);
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4MouseClicked(evt);
            }
        });
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, 110, 50));

        mainPa.setOpaque(false);
        mainPa.setLayout(new java.awt.BorderLayout());
        getContentPane().add(mainPa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 960, 470));

        closeL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/close.png"))); // NOI18N
        closeL.setText("jLabel11");
        closeL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLMouseClicked(evt);
            }
        });
        getContentPane().add(closeL, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 40, 30));

        blackL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/closeB.png"))); // NOI18N
        blackL.setText("jLabel17");
        blackL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                blackLMouseClicked(evt);
            }
        });
        getContentPane().add(blackL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 580));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/wddss.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 150));

        smView.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        smView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/ssssmmm.png"))); // NOI18N
        smView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 2));
        smView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                smViewMouseClicked(evt);
            }
        });
        getContentPane().add(smView, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 70, 50));

        lmView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/444th.png"))); // NOI18N
        lmView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 2));
        lmView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lmViewMouseClicked(evt);
            }
        });
        getContentPane().add(lmView, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 70, 50));

        tmView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/ttttmmmm.png"))); // NOI18N
        tmView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 2));
        tmView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tmViewMouseClicked(evt);
            }
        });
        getContentPane().add(tmView, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 70, 50));

        fmView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/fffmmm.png"))); // NOI18N
        fmView.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 102), 2));
        fmView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fmViewMouseClicked(evt);
            }
        });
        getContentPane().add(fmView, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 70, 50));

        mmFirstL.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        mmFirstL.setForeground(new java.awt.Color(255, 255, 255));
        mmFirstL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mmFirstL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/mvsl.png"))); // NOI18N
        mmFirstL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mmFirstLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mmFirstLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mmFirstLMouseExited(evt);
            }
        });
        getContentPane().add(mmFirstL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 170, 60));

        mmSecondL.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        mmSecondL.setForeground(new java.awt.Color(255, 255, 255));
        mmSecondL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mmSecondL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/moviMa.png"))); // NOI18N
        mmSecondL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mmSecondLMouseClicked(evt);
            }
        });
        getContentPane().add(mmSecondL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 170, 60));

        usFirstL.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        usFirstL.setForeground(new java.awt.Color(255, 255, 255));
        usFirstL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usFirstL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/use2.png"))); // NOI18N
        usFirstL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usFirstLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usFirstLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usFirstLMouseExited(evt);
            }
        });
        getContentPane().add(usFirstL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 170, 70));

        usSecondL.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        usSecondL.setForeground(new java.awt.Color(255, 255, 255));
        usSecondL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usSecondL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/userM.png"))); // NOI18N
        usSecondL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usSecondLMouseClicked(evt);
            }
        });
        getContentPane().add(usSecondL, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 170, 70));

        fl.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        fl.setForeground(new java.awt.Color(255, 255, 255));
        fl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/22.png"))); // NOI18N
        fl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                flMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                flMouseExited(evt);
            }
        });
        getContentPane().add(fl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 170, 60));

        sl.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        sl.setForeground(new java.awt.Color(255, 255, 255));
        sl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/cinam.png"))); // NOI18N
        sl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slMouseClicked(evt);
            }
        });
        getContentPane().add(sl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 170, 60));

        uIDLabel.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        uIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        uIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        uIDLabel.setText("962160");
        getContentPane().add(uIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 130, 20));

        uNameLabel.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 14)); // NOI18N
        uNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        uNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        uNameLabel.setText("Sanu Vithanage");
        getContentPane().add(uNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 150, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/close.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 40, 30));

        clock.setFont(new java.awt.Font("DS-Digital", 0, 24)); // NOI18N
        clock.setForeground(new java.awt.Color(204, 204, 255));
        clock.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clock.setText("05:10:00 P.M");
        getContentPane().add(clock, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 130, 30));

        date.setFont(new java.awt.Font("DS-Digital", 0, 24)); // NOI18N
        date.setForeground(new java.awt.Color(204, 204, 255));
        date.setText("2016-08-05");
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 130, -1));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/rser.png"))); // NOI18N
        jButton8.setContentAreaFilled(false);
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 130, 50));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/fwwd.png"))); // NOI18N
        jButton9.setContentAreaFilled(false);
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 110, 50));

        backupBtn.setBackground(new java.awt.Color(255, 255, 255));
        backupBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/bbbccc.png"))); // NOI18N
        backupBtn.setContentAreaFilled(false);
        backupBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backupBtnMouseClicked(evt);
            }
        });
        backupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backupBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, 140, 50));

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/lggout.png"))); // NOI18N
        jButton11.setContentAreaFilled(false);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 110, 120, 50));

        movieTwoL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/movie2.jpg"))); // NOI18N
        movieTwoL.setText("jLabel5");
        movieTwoL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 2, true));
        movieTwoL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movieTwoLMouseClicked(evt);
            }
        });
        getContentPane().add(movieTwoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 170, 270));

        movieThreeL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/movie3.jpg"))); // NOI18N
        movieThreeL.setText("jLabel5");
        movieThreeL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 2, true));
        movieThreeL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movieThreeLMouseClicked(evt);
            }
        });
        getContentPane().add(movieThreeL, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 170, 270));

        movieFourL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/movie4.jpg"))); // NOI18N
        movieFourL.setText("jLabel5");
        movieFourL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 2, true));
        movieFourL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movieFourLMouseClicked(evt);
            }
        });
        getContentPane().add(movieFourL, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, 170, 270));

        movieOneL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/movie1.jpg"))); // NOI18N
        movieOneL.setText("jLabel5");
        movieOneL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 255), 2, true));
        movieOneL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                movieOneLMouseClicked(evt);
            }
        });
        getContentPane().add(movieOneL, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 170, 270));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Savoy 3D");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 430, 80));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/sry1.png"))); // NOI18N
        jLabel3.setText("close");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 990, 230));

        filmOneButton.setBackground(new java.awt.Color(255, 51, 153));
        filmOneButton.setForeground(new java.awt.Color(255, 255, 255));
        filmOneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/spg.png"))); // NOI18N
        filmOneButton.setBorder(null);
        filmOneButton.setContentAreaFilled(false);
        filmOneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filmOneButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                filmOneButtonMouseEntered(evt);
            }
        });
        getContentPane().add(filmOneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, 130, 40));

        filmThreeButton.setBackground(new java.awt.Color(255, 51, 153));
        filmThreeButton.setForeground(new java.awt.Color(255, 255, 255));
        filmThreeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/spg.png"))); // NOI18N
        filmThreeButton.setBorder(null);
        filmThreeButton.setContentAreaFilled(false);
        filmThreeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filmThreeButtonMouseClicked(evt);
            }
        });
        filmThreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmThreeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(filmThreeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, 130, 40));

        filnFourButton.setBackground(new java.awt.Color(255, 51, 153));
        filnFourButton.setForeground(new java.awt.Color(255, 255, 255));
        filnFourButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/spg.png"))); // NOI18N
        filnFourButton.setBorder(null);
        filnFourButton.setContentAreaFilled(false);
        filnFourButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filnFourButtonMouseClicked(evt);
            }
        });
        getContentPane().add(filnFourButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 500, 130, 40));

        titleM1.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        titleM1.setForeground(new java.awt.Color(51, 153, 0));
        titleM1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleM1.setText("Maya Sinhala Movie");
        getContentPane().add(titleM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, 170, 20));

        titleM3.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        titleM3.setForeground(new java.awt.Color(51, 153, 0));
        titleM3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleM3.setText("Jack Reacher English Movie");
        getContentPane().add(titleM3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 170, 20));

        titleM2.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        titleM2.setForeground(new java.awt.Color(51, 153, 0));
        titleM2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleM2.setText("Inferno Englis Movie");
        getContentPane().add(titleM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 170, 20));

        titleM4.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        titleM4.setForeground(new java.awt.Color(51, 153, 0));
        titleM4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleM4.setText("Remo Tamil Movie");
        getContentPane().add(titleM4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, 170, 20));

        filmTwoButton.setBackground(new java.awt.Color(255, 51, 153));
        filmTwoButton.setForeground(new java.awt.Color(255, 255, 255));
        filmTwoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/spg.png"))); // NOI18N
        filmTwoButton.setBorder(null);
        filmTwoButton.setContentAreaFilled(false);
        filmTwoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                filmTwoButtonMouseClicked(evt);
            }
        });
        getContentPane().add(filmTwoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 500, 130, 40));

        movieTt3.setBackground(new java.awt.Color(255, 255, 255));
        movieTt3.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        movieTt3.setForeground(new java.awt.Color(255, 0, 51));
        movieTt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        movieTt3.setText("4:00 pm");
        getContentPane().add(movieTt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 460, 160, -1));

        movieTt2.setBackground(new java.awt.Color(255, 255, 255));
        movieTt2.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        movieTt2.setForeground(new java.awt.Color(255, 0, 51));
        movieTt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        movieTt2.setText("1:15 pm");
        getContentPane().add(movieTt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 460, 160, -1));

        movieTt4.setBackground(new java.awt.Color(255, 255, 255));
        movieTt4.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        movieTt4.setForeground(new java.awt.Color(255, 0, 51));
        movieTt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        movieTt4.setText("7:00 pm");
        getContentPane().add(movieTt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 460, 160, -1));

        movieTt1.setBackground(new java.awt.Color(255, 255, 255));
        movieTt1.setFont(new java.awt.Font("Tekton Pro Ext", 0, 18)); // NOI18N
        movieTt1.setForeground(new java.awt.Color(255, 0, 51));
        movieTt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        movieTt1.setText("10:30 am");
        getContentPane().add(movieTt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 460, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/cdcdc copy.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 780, 430));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/fggf.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 230, 410));

        animationL.setBackground(new java.awt.Color(0, 0, 0));
        animationL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/dnvd.gif"))); // NOI18N
        getContentPane().add(animationL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked

    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void backupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backupBtnActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed

        // new Loging().setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void movieOneLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movieOneLMouseClicked
        new com.ijse.theaterbooking.view.FirstFilm().play();
    }//GEN-LAST:event_movieOneLMouseClicked

    private void movieTwoLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movieTwoLMouseClicked
        new com.ijse.theaterbooking.view.SecondFilm().play();
    }//GEN-LAST:event_movieTwoLMouseClicked

    private void movieThreeLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movieThreeLMouseClicked
        new com.ijse.theaterbooking.view.ThirdFilm().play();
    }//GEN-LAST:event_movieThreeLMouseClicked

    private void movieFourLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movieFourLMouseClicked
        new com.ijse.theaterbooking.view.FourthFilm().play();
    }//GEN-LAST:event_movieFourLMouseClicked

    private void blackLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_blackLMouseClicked

    }//GEN-LAST:event_blackLMouseClicked

    private void filmOneButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filmOneButtonMouseClicked
        filmOneProcess();

    }//GEN-LAST:event_filmOneButtonMouseClicked

    private void filmTwoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filmTwoButtonMouseClicked

        filmTwoProcess();


    }//GEN-LAST:event_filmTwoButtonMouseClicked

    private void closeLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLMouseClicked
        mainPa.removeAll();
        blackL.setVisible(false);
        mainPa.setVisible(false);
        closeL.setVisible(false);
        com.ijse.theaterbooking.view.GoldClassBook.resDetails.removeAll(resDetails);
        com.ijse.theaterbooking.view.GoldClassBook.count = 0;
        if (emp != null) {
            emp.stop();
        }
        btn1.setVisible(false);
        btn2.setVisible(false);
        btn3.setVisible(false);
        btn4.setVisible(false);
        dateDate.setVisible(false);
        gt1.setVisible(false);
    }//GEN-LAST:event_closeLMouseClicked

    private void filmThreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmThreeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filmThreeButtonActionPerformed

    private void filmThreeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filmThreeButtonMouseClicked
        thirdFilmProcess();


    }//GEN-LAST:event_filmThreeButtonMouseClicked

    private void filnFourButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filnFourButtonMouseClicked
        fourthFilmProcess();


    }//GEN-LAST:event_filnFourButtonMouseClicked

    private void slMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slMouseClicked
        if (userId.equals("01122")) {
            try {
                com.ijse.theaterbooking.view.CinamaManager cm = new com.ijse.theaterbooking.view.CinamaManager();
                blackL.setVisible(true);
                closeL.setVisible(true);
                cm.setVisible(true);
                mainPa.setVisible(true);
                mainPa.removeAll();
                mainPa.add(cm);
                mainPa.updateUI();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Sorry Users Unable To Accses\n Please Contact Customer Service..!");
        }


    }//GEN-LAST:event_slMouseClicked


    private void mmSecondLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmSecondLMouseClicked

        if (userId.equals("01122")) {
            com.ijse.theaterbooking.view.MovieManage mm = new com.ijse.theaterbooking.view.MovieManage();
            blackL.setVisible(true);
            closeL.setVisible(true);
            mm.setVisible(true);
            mainPa.setVisible(true);
            mainPa.removeAll();
            mainPa.add(mm);
            mainPa.updateUI();
        } else {
            JOptionPane.showMessageDialog(this, "Sorry Users Unable To Accses\n Please Contact Customer Service..!");
        }

    }//GEN-LAST:event_mmSecondLMouseClicked

    private void usSecondLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usSecondLMouseClicked
        if (userId.equals("01122")) {
            try {
                com.ijse.theaterbooking.view.UserManager um = new com.ijse.theaterbooking.view.UserManager();
                blackL.setVisible(true);
                closeL.setVisible(true);
                um.setVisible(true);
                mainPa.setVisible(true);
                mainPa.removeAll();
                mainPa.add(um);
                mainPa.updateUI();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Sorry Users Unable To Accses\n Please Contact Customer Service..!");
        }


    }//GEN-LAST:event_usSecondLMouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked


    }//GEN-LAST:event_jButton9MouseClicked

    private void flMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flMouseClicked

    }//GEN-LAST:event_flMouseClicked

    private void flMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flMouseEntered
        fl.setVisible(false);
        sl.setVisible(true);
    }//GEN-LAST:event_flMouseEntered

    private void flMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flMouseExited
        sl.setVisible(false);
        fl.setVisible(true);
    }//GEN-LAST:event_flMouseExited

    private void backupBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backupBtnMouseClicked
        if (userId.equals("01122")) {
            try {
                dataBackup();

            } catch (IOException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Sorry Users Unable To Accses\n Please Contact Customer Service..!");
        }

    }//GEN-LAST:event_backupBtnMouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        if (userId.equals("01122")) {
            int res = JOptionPane.showConfirmDialog(HomePage.this, "Do you Really \nwant to Reset Database?", "Warning", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (res == JOptionPane.YES_OPTION) {

                try {
                    checkFile();
                    dataBackup();
                    if (true) {
                        JOptionPane.showMessageDialog(this, "Data Backup \n and Reset Compleated..!");
                    }
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NotBoundException ex) {
                    Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Sorry Users Unable To Accses\n Please Contact Customer Service..!");
        }


    }//GEN-LAST:event_jButton8MouseClicked

    private void usFirstLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usFirstLMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_usFirstLMouseClicked

    private void mmFirstLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmFirstLMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mmFirstLMouseClicked

    private void usFirstLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usFirstLMouseEntered
        usFirstL.setVisible(false);
        usSecondL.setVisible(true);
    }//GEN-LAST:event_usFirstLMouseEntered

    private void usFirstLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usFirstLMouseExited
        usSecondL.setVisible(false);
        usFirstL.setVisible(true);
    }//GEN-LAST:event_usFirstLMouseExited

    private void mmFirstLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmFirstLMouseEntered
        mmFirstL.setVisible(false);
        mmSecondL.setVisible(true);
    }//GEN-LAST:event_mmFirstLMouseEntered

    private void mmFirstLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmFirstLMouseExited
        mmSecondL.setVisible(false);
        mmFirstL.setVisible(true);
    }//GEN-LAST:event_mmFirstLMouseExited

    private void filmOneButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_filmOneButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_filmOneButtonMouseEntered

    private void fmViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fmViewMouseClicked

        if (userId.equals("01122")) {
            try {
                FirstMovieView fmView = new FirstMovieView(" ", " ", " ");
                blackL.setVisible(true);
                closeL.setVisible(true);
                fmView.setVisible(true);
                mainPa.setVisible(true);
                mainPa.removeAll();
                mainPa.add(fmView);
                mainPa.updateUI();
                dateDate.setVisible(true);
                btn1.setVisible(true);
                gt1.setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            try {
                Date nowD = new Date();
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String bDate = dateFormat.format(nowD);
                FirstMovieView fmView = new FirstMovieView(" ", " ", bDate);
                blackL.setVisible(true);
                closeL.setVisible(true);
                fmView.setVisible(true);
                mainPa.setVisible(true);
                mainPa.removeAll();
                mainPa.add(fmView);
                mainPa.updateUI();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_fmViewMouseClicked

    private void smViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_smViewMouseClicked

        if (userId.equals("01122")) {
            try {
                SecondMoviView fmView = new SecondMoviView(" ", " ", " ");
                blackL.setVisible(true);
                closeL.setVisible(true);
                fmView.setVisible(true);
                mainPa.setVisible(true);
                mainPa.removeAll();
                mainPa.add(fmView);
                mainPa.updateUI();
                dateDate.setVisible(true);
                btn2.setVisible(true);
                gt1.setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            try {
                Date nowD = new Date();
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String bDate = dateFormat.format(nowD);
                SecondMoviView fmView = new SecondMoviView(" ", " ", bDate);
                blackL.setVisible(true);
                closeL.setVisible(true);
                fmView.setVisible(true);
                mainPa.setVisible(true);
                mainPa.removeAll();
                mainPa.add(fmView);
                mainPa.updateUI();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_smViewMouseClicked

    private void tmViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmViewMouseClicked
        if (userId.equals("01122")) {
            try {
                ThirdMoviView fmView = new ThirdMoviView(" ", " ", " ");
                blackL.setVisible(true);
                closeL.setVisible(true);
                fmView.setVisible(true);
                mainPa.setVisible(true);
                mainPa.removeAll();
                mainPa.add(fmView);
                mainPa.updateUI();
                dateDate.setVisible(true);
                btn3.setVisible(true);
                gt1.setVisible(true);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            try {
                Date nowD = new Date();
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String bDate = dateFormat.format(nowD);
                ThirdMoviView fmView = new ThirdMoviView(" ", " ", bDate);
                blackL.setVisible(true);
                closeL.setVisible(true);
                fmView.setVisible(true);
                mainPa.setVisible(true);
                mainPa.removeAll();
                mainPa.add(fmView);
                mainPa.updateUI();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(HomePage.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_tmViewMouseClicked

    private void lmViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lmViewMouseClicked
        if (userId.equals("01122")) {
            try {
                LastMoviView fmView = new LastMoviView(" ", " ", " ");
                blackL.setVisible(true);
                closeL.setVisible(true);
                fmView.setVisible(true);
                mainPa.setVisible(true);
                mainPa.removeAll();
                mainPa.add(fmView);
                mainPa.updateUI();
                dateDate.setVisible(true);
                btn4.setVisible(true);
                gt1.setVisible(true);

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            try {
                Date nowD = new Date();
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String bDate = dateFormat.format(nowD);
                LastMoviView fmView = new LastMoviView(" ", " ", bDate);
                blackL.setVisible(true);
                closeL.setVisible(true);
                fmView.setVisible(true);
                mainPa.setVisible(true);
                mainPa.removeAll();
                mainPa.add(fmView);
                mainPa.updateUI();

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_lmViewMouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        this.dispose();
        new Loging().setVisible(true);
    }//GEN-LAST:event_jButton11MouseClicked

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        Date dat = dateDate.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String bDate = dateFormat.format(dat);
        if (bDate != null) {
            try {
                FirstMovieView fmView = new FirstMovieView(" ", " ", bDate);
                blackL.setVisible(true);
                closeL.setVisible(true);
                fmView.setVisible(true);
                mainPa.setVisible(true);
                mainPa.removeAll();
                mainPa.add(fmView);
                mainPa.updateUI();

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Please select a date first..!");
        }

    }//GEN-LAST:event_btn1MouseClicked

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
        Date dat = dateDate.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String bDate = dateFormat.format(dat);
        if (bDate != null) {
            try {
                SecondMoviView fmView = new SecondMoviView(" ", " ", bDate);
                blackL.setVisible(true);
                closeL.setVisible(true);
                fmView.setVisible(true);
                mainPa.setVisible(true);
                mainPa.removeAll();
                mainPa.add(fmView);
                mainPa.updateUI();

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a date first..!");
        }

    }//GEN-LAST:event_btn2MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
        Date dat = dateDate.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String bDate = dateFormat.format(dat);
        if (bDate != null) {
            try {
                ThirdMoviView fmView = new ThirdMoviView(" ", " ", bDate);
                blackL.setVisible(true);
                closeL.setVisible(true);
                fmView.setVisible(true);
                mainPa.setVisible(true);
                mainPa.removeAll();
                mainPa.add(fmView);
                mainPa.updateUI();

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a date first..!");
        }

    }//GEN-LAST:event_btn3MouseClicked

    private void btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseClicked
        Date dat = dateDate.getDate();
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String bDate = dateFormat.format(dat);
        if (bDate != null) {
            try {
                LastMoviView fmView = new LastMoviView(" ", " ", bDate);
                blackL.setVisible(true);
                closeL.setVisible(true);
                fmView.setVisible(true);
                mainPa.setVisible(true);
                mainPa.removeAll();
                mainPa.add(fmView);
                mainPa.updateUI();

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            } catch (NotBoundException ex) {
                Logger.getLogger(HomePage.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a date first..!");
        }

    }//GEN-LAST:event_btn4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel animationL;
    private javax.swing.JButton backupBtn;
    public static javax.swing.JLabel blackL;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JLabel clock;
    public static javax.swing.JLabel closeL;
    private javax.swing.JLabel date;
    private com.toedter.calendar.JDateChooser dateDate;
    private javax.swing.JButton filmOneButton;
    private javax.swing.JButton filmThreeButton;
    private javax.swing.JButton filmTwoButton;
    private javax.swing.JButton filnFourButton;
    private javax.swing.JLabel fl;
    private javax.swing.JLabel fmView;
    private javax.swing.JLabel gt1;
    public static javax.swing.JButton jButton11;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lmView;
    public static javax.swing.JPanel mainPa;
    private javax.swing.JLabel mmFirstL;
    private javax.swing.JLabel mmSecondL;
    private javax.swing.JLabel movieFourL;
    private javax.swing.JLabel movieOneL;
    private javax.swing.JLabel movieThreeL;
    private javax.swing.JLabel movieTt1;
    private javax.swing.JLabel movieTt2;
    private javax.swing.JLabel movieTt3;
    private javax.swing.JLabel movieTt4;
    private javax.swing.JLabel movieTwoL;
    private javax.swing.JLabel sl;
    private javax.swing.JLabel smView;
    private javax.swing.JLabel titleM1;
    private javax.swing.JLabel titleM2;
    private javax.swing.JLabel titleM3;
    private javax.swing.JLabel titleM4;
    private javax.swing.JLabel tmView;
    private javax.swing.JLabel uIDLabel;
    private javax.swing.JLabel uNameLabel;
    private javax.swing.JLabel usFirstL;
    private javax.swing.JLabel usSecondL;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        Date now = new Date();
        SimpleDateFormat sf = new SimpleDateFormat("yyyy - MM - dd");
        date.setText(sf.format(now));
    }
    int timeRun = 0;

    private void setTime() {
        new Thread() {
            public void run() {
                while (timeRun == 0) {

                    cal = new GregorianCalendar();
                    int hour = cal.get(Calendar.HOUR);
                    int min = cal.get(Calendar.MINUTE);
                    int sec = cal.get(Calendar.SECOND);
                    int AM_PM = cal.get(Calendar.AM_PM);

                    day_night = "";
                    if (AM_PM == 1) {
                        day_night = "PM";
                    } else {
                        day_night = "AM";
                    }

                    time1 = hour + ":" + min + ":" + sec + " " + day_night;
                    clock.setText(time1);

                }
            }
        }.start();
    }

    private void setMoviUpdates() throws ClassNotFoundException, NotBoundException, MalformedURLException, RemoteException, SQLException, IOException, FileNotFoundException, ParseException {
        MovieController movieController = ServerConnector.getServerConnector().getMovieController();
        Movies searchMovie = movieController.searchMovie("mov1");
        if (searchMovie != null) {
            movieTt1.setText(searchMovie.getMovieTime());
            titleM1.setText(searchMovie.getMovieName());
            String one = searchMovie.getMovieImageId();
            if (one.equals("movie1.jpg")) {
                movieOneL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/movie1.jpg")));
            }
        }

        Movies m2 = movieController.searchMovie("mov2");
        if (m2 != null) {
            movieTt2.setText(m2.getMovieTime());
            titleM2.setText(m2.getMovieName());
            String two = m2.getMovieImageId();
            if (two.equals("movie2.jpg")) {
                movieTwoL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/movie2.jpg")));
            }
        }

        Movies m3 = movieController.searchMovie("mov3");
        if (m3 != null) {
            movieTt3.setText(m3.getMovieTime());
            titleM3.setText(m3.getMovieName());
            String three = m3.getMovieImageId();
            if (three.equals("movie3.jpg")) {
                movieThreeL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/movie3.jpg")));
            }
        }

        Movies m4 = movieController.searchMovie("mov4");
        if (m4 != null) {
            movieTt4.setText(m4.getMovieTime());
            titleM4.setText(m4.getMovieName());
            String four = m4.getMovieImageId();
            if (four.equals("movie4.jpg")) {
                movieFourL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/movie4.jpg")));
            }
        }
    }

    private void setUser() {
        uNameLabel.setText(userName);
        uIDLabel.setText(userId);
    }

    private void checkFile() throws ClassNotFoundException, FileNotFoundException, SQLException, IOException, RemoteException, NotBoundException, ParseException {
        BookDetailsController bdc = ServerConnector.getServerConnector().getBookDetailsController();
        boolean res = bdc.checkFile();
        if (res) {
            System.out.println("empty");
        } else {
            System.out.println("notempty");
        }

    }

    private void dataBackup() throws IOException {

        File srcFolder = new File("E:\\IJSE\\J A V A\\3 rd Semester\\Main Projects\\Softaer Updates\\012\\Theater Ticket Booking\\TheaterBookingServer\\src\\com\\ijse\\theaterbooking\\file\\");
        String destFolder = new String("C:\\Users\\Sanu Vithanage\\Documents\\bacup\\");

        copyDirectory(srcFolder, destFolder);
        JOptionPane.showMessageDialog(this, noOfFiles + " Files Backup Compleated");
        System.out.println("No Of Files got Backuped from Source ::" + noOfFiles);
        System.out.println("Successfully Backup");

    }

    public void filmOneProcess() {
        try {
            String mTit1 = titleM1.getText();
            String mTim1 = movieTt1.getText();
            String uName = uNameLabel.getText();
            String uId = uIDLabel.getText();

//            MovieController mc=ServerConnector.getServerConnector().getMovieController();
//            mc.
            com.ijse.theaterbooking.view.BookingStepOne bso = new com.ijse.theaterbooking.view.BookingStepOne(mTit1, mTim1, uName, uId, "mov1");
            blackL.setVisible(true);
            closeL.setVisible(true);
            bso.setVisible(true);
            mainPa.setVisible(true);
            mainPa.removeAll();
            mainPa.add(bso);
            mainPa.updateUI();

        } catch (ParseException ex) {
            Logger.getLogger(HomePage.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void filmTwoProcess() {
        try {
            String mTit = titleM2.getText();
            String mTim = movieTt2.getText();
            String uName = uNameLabel.getText();
            String uId = uIDLabel.getText();

            com.ijse.theaterbooking.view.BookingStepOne bso = new com.ijse.theaterbooking.view.BookingStepOne(mTit, mTim, uName, uId, "mov2");
            blackL.setVisible(true);
            closeL.setVisible(true);
            bso.setVisible(true);
            mainPa.setVisible(true);
            mainPa.removeAll();
            mainPa.add(bso);
            mainPa.updateUI();

        } catch (ParseException ex) {
            Logger.getLogger(HomePage.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void thirdFilmProcess() {
        String mTit3 = titleM3.getText();
        String mTim3 = movieTt3.getText();
        String uName = uNameLabel.getText();
        String uId = uIDLabel.getText();

        com.ijse.theaterbooking.view.BookingStepOne bso = null;
        try {
            bso = new com.ijse.theaterbooking.view.BookingStepOne(mTit3, mTim3, uName, uId, "mov3");

        } catch (ParseException ex) {
            Logger.getLogger(HomePage.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
        blackL.setVisible(true);
        closeL.setVisible(true);
        bso.setVisible(true);
        mainPa.setVisible(true);
        mainPa.removeAll();
        mainPa.add(bso);
        mainPa.updateUI();
    }

    private void fourthFilmProcess() {
        try {
            String mTit4 = titleM4.getText();
            String mTim4 = movieTt4.getText();
            String uName = uNameLabel.getText();
            String uId = uIDLabel.getText();

            com.ijse.theaterbooking.view.BookingStepOne bso = new com.ijse.theaterbooking.view.BookingStepOne(mTit4, mTim4, uName, uId, "mov4");
            blackL.setVisible(true);
            closeL.setVisible(true);
            bso.setVisible(true);
            mainPa.setVisible(true);
            mainPa.removeAll();
            mainPa.add(bso);
            mainPa.updateUI();

        } catch (ParseException ex) {
            Logger.getLogger(HomePage.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }
    ///DATA BACUP////
    private File targetFolder;
    private int noOfFiles;

    public void copyDirectory(File sourceLocation, String destLocation)
            throws IOException {
        targetFolder = new File(destLocation);
        if (sourceLocation.isDirectory()) {
            if (!targetFolder.exists()) {
                targetFolder.mkdir();
            }

            String[] children = sourceLocation.list();
            for (int i = 0; i < children.length; i++) {
                copyDirectory(new File(sourceLocation, children[i]),
                        destLocation);

            }
        } else {

            InputStream in = new FileInputStream(sourceLocation);
            OutputStream out = new FileOutputStream(targetFolder + "\\" + sourceLocation.getName(), true);
            System.out.println("Destination Path ::" + targetFolder + "\\" + sourceLocation.getName());
            // Copy the bits from instream to outstream
            byte[] buf = new byte[1024];
            int len;
            while ((len = in.read(buf)) > 0) {
                out.write(buf, 0, len);
            }
            in.close();
            out.close();
            noOfFiles++;

        }

    }
}
