/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ijse.theaterbooking.view;

import com.ijse.theaterbooking.connector.ServerConnector;
import com.ijse.theaterbooking.controller.BookController;
import com.ijse.theaterbooking.controller.BookDetailsController;
import java.net.MalformedURLException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import com.ijse.theaterbooking.model.Book;
import com.ijse.theaterbooking.model.BookDetails;
import com.ijse.theaterbooking.model.GoldClass;
import com.ijse.theaterbooking.validation.Validation;
import static com.ijse.theaterbooking.view.GoldClassBook.resDetails;
import static com.ijse.theaterbooking.view.HomePage.blackL;
import static com.ijse.theaterbooking.view.HomePage.mainPa;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.HashMap;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Sanu Vithanage
 */
public class LastStep extends javax.swing.JPanel {

    private String userName;
    private String userID;
    private String movieName;
    private String movieTime;
    private ArrayList<String> seatDetails;
    private String bookId;
    private String bookDate;
    private String filmID;
    private double totalPrice;
    private boolean response = false;
    private boolean response2 = false;
    com.ijse.theaterbooking.view.HomePage h;

    /**
     * Creates new form BookingStepOne
     *///userName, bookId, bookDate, userID, movieName, movieTime, resDetails
    public LastStep(String userName, String bookId, String bookDate, String userID, String movieName, String movieTime, ArrayList<String> seatDetails, String filmID, double totalPrice) {
        initComponents();
        this.userName = userName;
        this.userID = userID;
        this.movieTime = movieTime;
        this.seatDetails = seatDetails;
        this.bookId = bookId;
        this.bookDate = bookDate;
        this.movieName = movieName;
        this.filmID = filmID;
        this.totalPrice = totalPrice;
        tableLoad();
        panelLoad();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lastButton = new javax.swing.JButton();
        movieNa = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        totalAmount = new javax.swing.JTextField();
        balance = new javax.swing.JTextField();
        sum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        creditCN = new javax.swing.JTextField();
        aa = new javax.swing.JTextField();
        cvv = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cPay = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailsTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1000, 580));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lastButton.setBackground(new java.awt.Color(255, 255, 255));
        lastButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/nenenext.png"))); // NOI18N
        lastButton.setContentAreaFilled(false);
        lastButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lastButtonMouseClicked(evt);
            }
        });
        lastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastButtonActionPerformed(evt);
            }
        });
        add(lastButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 400, 140, 60));

        movieNa.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 24)); // NOI18N
        movieNa.setForeground(new java.awt.Color(255, 255, 255));
        movieNa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        movieNa.setText("Booking Last Step");
        add(movieNa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 840, 60));

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        totalAmount.setEditable(false);
        totalAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalAmountActionPerformed(evt);
            }
        });
        totalAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                totalAmountKeyReleased(evt);
            }
        });
        jPanel2.add(totalAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 120, 30));

        balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceActionPerformed(evt);
            }
        });
        jPanel2.add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 120, 30));

        sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumActionPerformed(evt);
            }
        });
        sum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sumKeyReleased(evt);
            }
        });
        jPanel2.add(sum, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 120, 30));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 160, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Paid Amount");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Balance");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Total Price");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jTabbedPane1.addTab("Payby Cash", jPanel2);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        creditCN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                creditCNKeyReleased(evt);
            }
        });
        jPanel1.add(creditCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 150, 30));
        jPanel1.add(aa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 150, 30));

        cvv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cvvKeyReleased(evt);
            }
        });
        jPanel1.add(cvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 150, 30));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 150, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Total amount");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("CVV");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Email");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Card Number");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        cPay.setText("Proceed");
        jPanel1.add(cPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 150, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Date");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jTabbedPane1.addTab("Credi Card", jPanel1);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 360, 310));

        detailsTable.setBackground(new java.awt.Color(0, 0, 0));
        detailsTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        detailsTable.setForeground(new java.awt.Color(255, 255, 255));
        detailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SeatID", "Movie Name", "Movie Time", "Booking ID", "Price"
            }
        ));
        jScrollPane1.setViewportView(detailsTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 440, 310));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ijse/theaterbooking/view/images/tt2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 470));
    }// </editor-fold>//GEN-END:initComponents
    String sheetId;
    private void lastButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastButtonMouseClicked

        if (response) {
            try {

                BookController bookController = ServerConnector.getServerConnector().getBookController();
                BookDetailsController bookDetailsController = ServerConnector.getServerConnector().getBookDetailsController();

                Book book = new Book(bookId, bookDate, userID);
                ArrayList<BookDetails> bookDetails = new ArrayList<>();
                for (int i = 0; i < detailsTable.getRowCount(); i++) {
                    sheetId = (String) detailsTable.getValueAt(i, 0);
                    BookDetails bDetails = new BookDetails(bookId, filmID, sheetId, totalPrice, bookDate);
                    bookDetails.add(bDetails);
                    // System.out.println(bookId + " : " + movieTime + " : " + sheetId + " : " + totalPrice + " : " + filmID);
                    //System.out.println(bookDetails.get(i));
                }

                try {
                    BookController bookControllers = ServerConnector.getServerConnector().getBookController();
                    boolean addBook = bookControllers.addBooking(book, bookDetails);
                    if (addBook) {
                        JOptionPane.showMessageDialog(LastStep.this, "Your Booked Done ");
                        mainPa.removeAll();
                        blackL.setVisible(false);
                        mainPa.setVisible(false);
                        com.ijse.theaterbooking.view.HomePage.closeL.setVisible(false);
                        com.ijse.theaterbooking.view.GoldClassBook.resDetails.removeAll(resDetails);
                        com.ijse.theaterbooking.view.GoldClassBook.count = 0;

                        ///// ticket print///////
                        JOptionPane.showMessageDialog(this, "Thank you..Get Your Ticket");
                        DefaultTableModel tableModel2 = (DefaultTableModel) detailsTable.getModel();
                        try {
                            InputStream is = getClass().getResourceAsStream("ticket.jrxml");
                            JasperReport jr = JasperCompileManager.compileReport(is);
                            HashMap hm = new HashMap();
                            hm.put("movieN", movieName);
                            hm.put("uClass", "Gold Class");
                            hm.put("mTime", movieTime);
                            hm.put("bookingDate", bookDate);
                            hm.put("totalPr", totalPrice);
                            hm.put("bookingI", bookId);

                            JasperPrint jp = JasperFillManager.fillReport(jr, hm,  new JRTableModelDataSource(tableModel2));
                            JasperViewer.viewReport(jp);
                        } catch (JRException ex) {
                            Logger.getLogger(LastStep.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        //////////relese//////
                        BookController bc = ServerConnector.getServerConnector().getBookController();
                        if (filmID.equals("mov1")) {
                            bc.releaseMov1(sheetId);
                        }
                        if (filmID.equals("mov2")) {
                            bc.releaseMov2(sheetId);
                        }
                        if (filmID.equals("mov3")) {
                            bc.releaseMov3(sheetId);
                        }
                        if (filmID.equals("mov4")) {
                            bc.releaseMov4(sheetId);
                        }

                    } else {
                        JOptionPane.showMessageDialog(LastStep.this, "BooK Faild");
                        JOptionPane.showMessageDialog(LastStep.this, "Try Again Dont Select Alredy Booked Seats");
                        mainPa.removeAll();
                        blackL.setVisible(false);
                        mainPa.setVisible(false);
                        com.ijse.theaterbooking.view.HomePage.closeL.setVisible(false);
                        com.ijse.theaterbooking.view.GoldClassBook.resDetails.removeAll(resDetails);
                        com.ijse.theaterbooking.view.GoldClassBook.count = 0;
                    }

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(GoldClassBook.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(LastStep.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(LastStep.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(LastStep.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Throwable ex) {
                    Logger.getLogger(LastStep.class.getName()).log(Level.SEVERE, null, ex);
                }

            } catch (NotBoundException ex) {
                Logger.getLogger(GoldClassBook.class.getName()).log(Level.SEVERE, null, ex);
            } catch (MalformedURLException ex) {
                Logger.getLogger(GoldClassBook.class.getName()).log(Level.SEVERE, null, ex);
            } catch (RemoteException ex) {
                Logger.getLogger(GoldClassBook.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassCastException ex) {
                Logger.getLogger(GoldClassBook.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Complete The Payment For Booking");
        }


    }//GEN-LAST:event_lastButtonMouseClicked

    private void lastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastButtonActionPerformed

    private void totalAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalAmountActionPerformed

    private void balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balanceActionPerformed

    private void sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumActionPerformed
        double inputSum = Double.parseDouble(sum.getText());
        double totalAmo = Double.parseDouble(totalAmount.getText());
        if (totalAmo <= inputSum) {
            double balanc = inputSum - totalAmo;
            balance.setText(Double.toString(balanc));
            lastButton.enable();
            response = true;
        } else {
            JOptionPane.showMessageDialog(this, "Insufficent Credit");
            response = false;
        }

    }//GEN-LAST:event_sumActionPerformed

    private void totalAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalAmountKeyReleased

    }//GEN-LAST:event_totalAmountKeyReleased

    private void sumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sumKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Toolkit.getDefaultToolkit();
            Validation.priceText(sum);

        }
    }//GEN-LAST:event_sumKeyReleased

    private void creditCNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_creditCNKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Toolkit.getDefaultToolkit();
            Validation.numberOnly(creditCN);

        }
    }//GEN-LAST:event_creditCNKeyReleased

    private void cvvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cvvKeyReleased
        if (evt.getKeyCode() != KeyEvent.VK_BACK_SPACE) {
            Toolkit.getDefaultToolkit();
            Validation.numberOnly(cvv);

        }
    }//GEN-LAST:event_cvvKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aa;
    private javax.swing.JTextField balance;
    private javax.swing.JButton cPay;
    private javax.swing.JTextField creditCN;
    private javax.swing.JTextField cvv;
    private javax.swing.JTable detailsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JButton lastButton;
    private javax.swing.JLabel movieNa;
    private javax.swing.JTextField sum;
    private javax.swing.JTextField totalAmount;
    // End of variables declaration//GEN-END:variables

    private void nameSetin() {

    }

    private void tableLoad() {
        DefaultTableModel model = (DefaultTableModel) detailsTable.getModel();
        for (int i = 0; i < seatDetails.size(); i++) {
            String s1 = seatDetails.get(i);
            Object[] addTableS = {s1, movieName, movieTime, bookId, totalPrice};
            model.addRow(addTableS);
        }

    }

    private void panelLoad() {
        totalAmount.setText(Double.toString(totalPrice));
        aa.setText(Double.toString(totalPrice));

    }

}
